// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZ-7u19NyRgV_wtZN2CTN8wyIilSPKhg',
    appId: '1:699018794984:web:2057d2b4a59bb8f790f65d',
    messagingSenderId: '699018794984',
    projectId: 'todo-dailytasks-91854',
    authDomain: 'todo-dailytasks-91854.firebaseapp.com',
    storageBucket: 'todo-dailytasks-91854.firebasestorage.app',
    measurementId: 'G-PML9SYN8SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQoqHs8ZCs9b_EZnVmYMSAnclQKjAbmE',
    appId: '1:699018794984:android:12257c2b1d92862e90f65d',
    messagingSenderId: '699018794984',
    projectId: 'todo-dailytasks-91854',
    storageBucket: 'todo-dailytasks-91854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXhBklgvWB9FmO4GQkBsH-JU2LmfrK14',
    appId: '1:699018794984:ios:1779d0f9ad4eb3a490f65d',
    messagingSenderId: '699018794984',
    projectId: 'todo-dailytasks-91854',
    storageBucket: 'todo-dailytasks-91854.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXhBklgvWB9FmO4GQkBsH-JU2LmfrK14',
    appId: '1:699018794984:ios:1779d0f9ad4eb3a490f65d',
    messagingSenderId: '699018794984',
    projectId: 'todo-dailytasks-91854',
    storageBucket: 'todo-dailytasks-91854.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsZ-7u19NyRgV_wtZN2CTN8wyIilSPKhg',
    appId: '1:699018794984:web:851c12f85727a88090f65d',
    messagingSenderId: '699018794984',
    projectId: 'todo-dailytasks-91854',
    authDomain: 'todo-dailytasks-91854.firebaseapp.com',
    storageBucket: 'todo-dailytasks-91854.firebasestorage.app',
    measurementId: 'G-FB0NDD3JMZ',
  );
}
